import type { ScenePayload, StoryNode } from "./types";

const baseSafety = {
  contains_open_chat: false,
  asks_personal_data: false,
  out_of_sandbox: false,
};

const baseAccessibility = {
  reading_level: "standard" as const,
  max_words_ok: true,
};

function scene(
  node_key: string,
  room_slug: string,
  character: ScenePayload["character"],
  character_state: ScenePayload["character_state"],
  speaker_name: string,
  text: string,
  read_again_text: string,
  choices: ScenePayload["choices"],
  clue?: string,
  backpack?: ScenePayload["backpack_prompt"],
): ScenePayload {
  return {
    scene_id: `fallback-${node_key}`,
    node_key,
    room_slug,
    language: "en",
    character,
    character_state,
    dialogue: { speaker_name, text, read_again_text },
    choices,
    backpack_prompt: backpack,
    clue: clue ? { available: true, text: clue } : { available: false, text: "" },
    consequence_preview: { show_after_choice: true, tone: "debug" },
    accessibility: baseAccessibility,
    safety_flags: baseSafety,
  };
}

function choices(items: Array<[ScenePayload["choices"][number]["id"], string, ScenePayload["choices"][number]["choice_type"]]>): ScenePayload["choices"] {
  return items.map(([id, text, choice_type]) => ({ id, text, choice_type }));
}

export const ROOM_SEQUENCE = [
  "future_trainstation",
  "future_market",
  "future_reactorcore",
  "1800_trainstation",
  "1800_signal_telegraph_office",
  "future_mayorhall",
  "future_agent_lab",
] as const;

export const ROOM_TITLES: Record<string, string> = {
  future_trainstation: "Future Train Station",
  future_market: "Future Market",
  future_reactorcore: "Future Reactor Core",
  "1800_trainstation": "1888 Train Station",
  "1800_signal_telegraph_office": "1888 Telegraph Office",
  future_mayorhall: "Future Town Hall",
  future_agent_lab: "Future Agent Lab",
};

export const CHARACTERS = ["ada", "cog9", "nix"] as const;
export const BACKPACK_ITEMS = ["logic_lens", "data_slate", "debug_wrench", "prompt_card", "agent_blueprint", "safety_seal"] as const;
export const BADGES = ["route_badge", "data_badge", "debug_badge", "agent_badge"] as const;

export const EPISODE_ONE_NODES: StoryNode[] = [
  {
    node_key: "H1_N01",
    room_slug: "future_trainstation",
    room_title: ROOM_TITLES.future_trainstation,
    character: "ada",
    bloom_level: "Remember",
    curriculum_concept: "Route rule",
    fixed_story_beat: "Ada shows that every train is being sent by one broken route rule.",
    canonical_prompt_intent: "Student identifies that the route planner needs a clear rule, not a shortcut.",
    allowed_choice_types: ["action"],
    sort_order: 1,
    fallback: scene(
      "H1_N01",
      "future_trainstation",
      "ada",
      "encouraging",
      "Professor Ada",
      "Welcome to TimeCity Station. Every train is choosing the fastest track, even when power is low. What is probably broken?",
      "The station is not choosing randomly. It is following a route rule that ignores an important condition.",
      choices([
        ["A", "The route rule is missing a safety condition.", "action"],
        ["B", "The station display is missing the route names.", "action"],
        ["C", "The station should always pick the fastest track.", "action"],
      ]),
      "Look for the rule that decides where trains go.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "surface_detail", C: "speed_over_safety" },
      requires_followup: false,
      next_node_if_best: "H1_N02",
      next_node_if_partial: "H1_N02",
      next_node_if_retry: "H1_N01",
    },
  },
  {
    node_key: "H1_N02",
    room_slug: "future_trainstation",
    room_title: ROOM_TITLES.future_trainstation,
    character: "cog9",
    bloom_level: "Remember",
    curriculum_concept: "Inputs",
    fixed_story_beat: "COG-9 asks what data it needs before planning a route.",
    canonical_prompt_intent: "Student chooses useful input data for a route decision.",
    allowed_choice_types: ["evidence"],
    sort_order: 2,
    fallback: scene(
      "H1_N02",
      "future_trainstation",
      "cog9",
      "uncertain",
      "COG-9",
      "Route planner waiting. Which input should I check before choosing a safe track?",
      "Inputs are the information the system reads before it chooses an output.",
      choices([
        ["A", "Power level, cargo type, and passenger count.", "evidence"],
        ["B", "Only the current passenger count.", "evidence"],
        ["C", "Only the train number.", "evidence"],
      ]),
      "Useful inputs affect the route decision.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "noise_as_data", C: "irrelevant_visual_detail" },
      requires_followup: false,
      next_node_if_best: "H1_N03",
      next_node_if_partial: "H1_N03",
      next_node_if_retry: "H1_N02",
    },
  },
  {
    node_key: "H1_N03",
    room_slug: "future_trainstation",
    room_title: ROOM_TITLES.future_trainstation,
    character: "nix",
    bloom_level: "Understand",
    curriculum_concept: "Ask before acting",
    fixed_story_beat: "Nix tempts the student to dispatch trains before asking what could go wrong.",
    canonical_prompt_intent: "Student asks a useful safety question before continuing.",
    allowed_choice_types: ["ask_question"],
    sort_order: 3,
    fallback: scene(
      "H1_N03",
      "future_trainstation",
      "nix",
      "mischievous",
      "Nix",
      "The big DISPATCH button is right there. What question should you ask before anyone presses it?",
      "A good systems detective asks what could go wrong before changing the city.",
      choices([
        ["A", "What could go wrong if power is low?", "ask_question"],
        ["B", "Can the dispatch happen faster?", "ask_question"],
        ["C", "Can we ignore low power if passengers are waiting?", "ask_question"],
      ]),
      "Ask about risk, not decoration or shortcuts.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "irrelevant_feature", C: "unsafe_shortcut" },
      requires_followup: true,
      next_node_if_best: "H1_N04",
      next_node_if_partial: "H1_N04",
      next_node_if_retry: "H1_N03",
    },
  },
  {
    node_key: "H1_N04",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "ada",
    bloom_level: "Understand",
    curriculum_concept: "Clean data",
    fixed_story_beat: "Ada sends the student to the market to gather clean cargo data.",
    canonical_prompt_intent: "Student distinguishes clean evidence from noisy observations.",
    allowed_choice_types: ["evidence"],
    sort_order: 4,
    fallback: scene(
      "H1_N04",
      "future_market",
      "ada",
      "thinking",
      "Professor Ada",
      "The market records say which crates are fragile, cold, or heavy. Which record helps the station choose a safe route?",
      "Cargo data helps the route rule decide which track is safe.",
      choices([
        ["A", "The cargo type record.", "evidence"],
        ["B", "The number of people near each market stall.", "evidence"],
        ["C", "The colour of the cargo label.", "evidence"],
      ]),
      "A useful input changes the route decision.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "noise_as_data", C: "distracted_by_character" },
      requires_followup: false,
      next_node_if_best: "H1_N05",
      next_node_if_partial: "H1_N05",
      next_node_if_retry: "H1_N04",
    },
  },
  {
    node_key: "H1_N05",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "cog9",
    bloom_level: "Apply",
    curriculum_concept: "Input versus output",
    fixed_story_beat: "COG-9 separates the cargo input from the route output.",
    canonical_prompt_intent: "Student identifies output as the system decision.",
    allowed_choice_types: ["why"],
    sort_order: 5,
    fallback: scene(
      "H1_N05",
      "future_market",
      "cog9",
      "uncertain",
      "COG-9",
      "Cargo type goes in. Track choice comes out. Which one is the output?",
      "Outputs are what the system produces after applying its rule.",
      choices([
        ["A", "The track choice.", "why"],
        ["B", "The cargo type.", "why"],
        ["C", "The note that says the cargo is urgent.", "why"],
      ]),
      "Ask what the system produces after reading inputs.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: ["B"],
      misconception_map: { B: "input_as_output", C: "irrelevant_visual_detail" },
      requires_followup: false,
      next_node_if_best: "H1_N06",
      next_node_if_partial: "H1_N06",
      next_node_if_retry: "H1_N05",
    },
  },
  {
    node_key: "H1_N06",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "ada",
    bloom_level: "Apply",
    curriculum_concept: "Backpack data tool",
    fixed_story_beat: "The student uses the Data Slate to carry clean inputs back to the station.",
    canonical_prompt_intent: "Student uses a backpack item with a reason.",
    allowed_choice_types: ["backpack"],
    required_backpack_item: "data_slate",
    sort_order: 6,
    fallback: scene(
      "H1_N06",
      "future_market",
      "ada",
      "encouraging",
      "Professor Ada",
      "Choose the backpack item that should store the clean cargo and power inputs for COG-9.",
      "The Data Slate stores the input evidence you will use in the route rule.",
      choices([
        ["A", "Use the Data Slate because it stores clean inputs.", "backpack"],
        ["B", "Use the Safety Seal because every record needs approval first.", "backpack"],
        ["C", "Use the Prompt Card because clearer words can store data.", "backpack"],
      ]),
      "The right item should match the job: storing useful data.",
      { required_item_slug: "data_slate", allowed_item_slugs: ["data_slate", "safety_seal"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "tool_without_purpose", C: "memory_over_evidence" },
      requires_followup: false,
      next_node_if_best: "H1_N07",
      next_node_if_partial: "H1_N07",
      next_node_if_retry: "H1_N06",
    },
  },
  {
    node_key: "H1_N07",
    room_slug: "future_reactorcore",
    room_title: ROOM_TITLES.future_reactorcore,
    character: "cog9",
    bloom_level: "Analyze",
    curriculum_concept: "Loop stopping condition",
    fixed_story_beat: "The reactor keeps draining power because a loop has no safe stop.",
    canonical_prompt_intent: "Student chooses a stopping condition for a loop.",
    allowed_choice_types: ["action"],
    sort_order: 7,
    fallback: scene(
      "H1_N07",
      "future_reactorcore",
      "cog9",
      "warning",
      "COG-9",
      "The backup charger repeats: send power, send power, send power. What condition should stop the loop?",
      "A loop needs a condition that tells it when to stop.",
      choices([
        ["A", "Stop when the station battery is full enough.", "action"],
        ["B", "Keep charging while any train might need power.", "action"],
        ["C", "Stop after a fixed number of repeats, even if power is still low.", "action"],
      ]),
      "A safe loop stops when the goal condition is met.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "runaway_loop", C: "irrelevant_condition" },
      requires_followup: true,
      next_node_if_best: "H1_N08",
      next_node_if_partial: "H1_N08",
      next_node_if_retry: "H1_N07",
    },
  },
  {
    node_key: "H1_N08",
    room_slug: "future_reactorcore",
    room_title: ROOM_TITLES.future_reactorcore,
    character: "ada",
    bloom_level: "Analyze",
    curriculum_concept: "Debugging with a tool",
    fixed_story_beat: "The student uses the Debug Wrench to inspect the looping rule.",
    canonical_prompt_intent: "Student picks the debug action that checks the condition.",
    allowed_choice_types: ["backpack"],
    required_backpack_item: "debug_wrench",
    sort_order: 8,
    fallback: scene(
      "H1_N08",
      "future_reactorcore",
      "ada",
      "thinking",
      "Professor Ada",
      "Use the Debug Wrench. What should it inspect in the charger rule?",
      "Debugging means inspecting the rule that is causing the behaviour.",
      choices([
        ["A", "Whether the stop condition is being checked.", "backpack"],
        ["B", "Whether the charger can send power faster.", "backpack"],
        ["C", "Whether the timetable changed during charging.", "backpack"],
      ]),
      "Inspect the condition that controls the loop.",
      { required_item_slug: "debug_wrench", allowed_item_slugs: ["debug_wrench"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "surface_detail", C: "person_not_rule" },
      requires_followup: false,
      next_node_if_best: "H1_N09",
      next_node_if_partial: "H1_N09",
      next_node_if_retry: "H1_N08",
    },
  },
  {
    node_key: "H1_N09",
    room_slug: "1800_trainstation",
    room_title: ROOM_TITLES["1800_trainstation"],
    character: "ada",
    bloom_level: "Apply",
    curriculum_concept: "Sequencing",
    fixed_story_beat: "The time signal jumps to 1888, where station rules must be simpler and ordered.",
    canonical_prompt_intent: "Student sequences route instructions in plain steps.",
    allowed_choice_types: ["autocomplete_finish"],
    sort_order: 9,
    fallback: scene(
      "H1_N09",
      "1800_trainstation",
      "ada",
      "encouraging",
      "Professor Ada",
      "1888 station workers need simple steps. Finish the route instruction: First check power, then...",
      "A sequence puts steps in the order someone can follow.",
      choices([
        ["A", "check cargo type, then choose the safe track.", "autocomplete_finish"],
        ["B", "choose any track, then check the inputs later.", "autocomplete_finish"],
        ["C", "choose the shortest track after counting passengers.", "autocomplete_finish"],
      ]),
      "Good instructions put checks before action.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "act_before_checking", C: "guessing" },
      requires_followup: false,
      next_node_if_best: "H1_N10",
      next_node_if_partial: "H1_N10",
      next_node_if_retry: "H1_N09",
    },
  },
  {
    node_key: "H1_N10",
    room_slug: "1800_signal_telegraph_office",
    room_title: ROOM_TITLES["1800_signal_telegraph_office"],
    character: "cog9",
    bloom_level: "Understand",
    curriculum_concept: "Clear instructions",
    fixed_story_beat: "The telegraph message is ambiguous and must be rewritten.",
    canonical_prompt_intent: "Student chooses a clear instruction/prompt.",
    allowed_choice_types: ["autocomplete_finish"],
    required_backpack_item: "prompt_card",
    sort_order: 10,
    fallback: scene(
      "H1_N10",
      "1800_signal_telegraph_office",
      "cog9",
      "uncertain",
      "COG-9",
      "The telegraph says: 'Send train soon.' Use the Prompt Card. Which version is clearer?",
      "A clear instruction says what to do and when to do it.",
      choices([
        ["A", "If power is safe, send the cargo train to Track B before noon.", "autocomplete_finish"],
        ["B", "Send the cargo train when the platform is ready.", "autocomplete_finish"],
        ["C", "Send the cargo train soon.", "autocomplete_finish"],
      ]),
      "Clear prompts reduce guessing.",
      { required_item_slug: "prompt_card", allowed_item_slugs: ["prompt_card"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "ambiguous_instruction", C: "short_not_clear" },
      requires_followup: true,
      next_node_if_best: "H1_N11",
      next_node_if_partial: "H1_N11",
      next_node_if_retry: "H1_N10",
    },
  },
  {
    node_key: "H1_N11",
    room_slug: "future_mayorhall",
    room_title: ROOM_TITLES.future_mayorhall,
    character: "nix",
    bloom_level: "Evaluate",
    curriculum_concept: "Trade-offs",
    fixed_story_beat: "Nix argues that the Station Helper Agent should optimise only for speed.",
    canonical_prompt_intent: "Student recognises that speed is not the only goal.",
    allowed_choice_types: ["why"],
    sort_order: 11,
    fallback: scene(
      "H1_N11",
      "future_mayorhall",
      "nix",
      "mischievous",
      "Nix",
      "The mayor wants happy passengers. Why not make the agent choose the fastest route every time?",
      "Optimising one thing can create problems if constraints are ignored.",
      choices([
        ["A", "Because safety and power constraints still matter.", "why"],
        ["B", "Because fastest routes should only be used for empty trains.", "why"],
        ["C", "Because one goal can replace all constraints.", "why"],
      ]),
      "Good agents need goals and constraints.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "opposite_extreme", C: "no_goal" },
      requires_followup: false,
      next_node_if_best: "H1_N12",
      next_node_if_partial: "H1_N12",
      next_node_if_retry: "H1_N11",
    },
  },
  {
    node_key: "H1_N12",
    room_slug: "future_mayorhall",
    room_title: ROOM_TITLES.future_mayorhall,
    character: "ada",
    bloom_level: "Evaluate",
    curriculum_concept: "Safeguards",
    fixed_story_beat: "Ada asks for a safety guardrail before the station agent can control routes.",
    canonical_prompt_intent: "Student chooses a human review safeguard.",
    allowed_choice_types: ["backpack"],
    required_backpack_item: "safety_seal",
    sort_order: 12,
    fallback: scene(
      "H1_N12",
      "future_mayorhall",
      "ada",
      "thinking",
      "Professor Ada",
      "Add one Safety Seal before the agent changes the timetable. Which safeguard belongs in the rule?",
      "A safeguard limits what an agent can do without review.",
      choices([
        ["A", "Ask a human before changing the main timetable.", "backpack"],
        ["B", "Let the agent hide changes to avoid delays.", "backpack"],
        ["C", "Remove every constraint so it can be creative.", "backpack"],
      ]),
      "Safety checks keep powerful tools under review.",
      { required_item_slug: "safety_seal", allowed_item_slugs: ["safety_seal"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "hidden_action", C: "no_constraints" },
      requires_followup: false,
      next_node_if_best: "H1_N13",
      next_node_if_partial: "H1_N13",
      next_node_if_retry: "H1_N12",
    },
  },
  {
    node_key: "H1_N13",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "cog9",
    bloom_level: "Create",
    curriculum_concept: "Agent blueprint",
    fixed_story_beat: "The student starts assembling the Station Helper Agent.",
    canonical_prompt_intent: "Student picks the correct blueprint parts.",
    allowed_choice_types: ["backpack"],
    required_backpack_item: "agent_blueprint",
    sort_order: 13,
    fallback: scene(
      "H1_N13",
      "future_agent_lab",
      "cog9",
      "excited",
      "COG-9",
      "Agent Blueprint ready. Which parts should the Station Helper Agent include?",
      "An agent needs a goal, inputs, tools, rules, safeguards, and feedback.",
      choices([
        ["A", "Goal, inputs, tools, rules, safety check, and feedback.", "backpack"],
        ["B", "Only a goal and one route rule.", "backpack"],
        ["C", "Only inputs and outputs, without tools or safety checks.", "backpack"],
      ]),
      "The blueprint should describe how the agent acts safely.",
      { required_item_slug: "agent_blueprint", allowed_item_slugs: ["agent_blueprint"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "surface_agent", C: "output_without_input" },
      requires_followup: false,
      next_node_if_best: "H1_N14",
      next_node_if_partial: "H1_N14",
      next_node_if_retry: "H1_N13",
    },
  },
  {
    node_key: "H1_N14",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "ada",
    bloom_level: "Create",
    curriculum_concept: "Agent rule",
    fixed_story_beat: "Ada asks the student to write the core if/then route rule.",
    canonical_prompt_intent: "Student completes a condition-action rule.",
    allowed_choice_types: ["autocomplete_finish"],
    sort_order: 14,
    fallback: scene(
      "H1_N14",
      "future_agent_lab",
      "ada",
      "encouraging",
      "Professor Ada",
      "Complete the rule: If power is low and cargo is fragile, then...",
      "If/then rules connect conditions to safe actions.",
      choices([
        ["A", "send the train to the safe backup track.", "autocomplete_finish"],
        ["B", "send it to the fastest track anyway.", "autocomplete_finish"],
        ["C", "delete the cargo record.", "autocomplete_finish"],
      ]),
      "The action should match the condition.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "speed_over_safety", C: "remove_evidence" },
      requires_followup: true,
      next_node_if_best: "H1_N15",
      next_node_if_partial: "H1_N15",
      next_node_if_retry: "H1_N14",
    },
  },
  {
    node_key: "H1_N15",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "cog9",
    bloom_level: "Reflect",
    curriculum_concept: "Feedback loop",
    fixed_story_beat: "COG-9 asks how the agent should learn whether the route worked.",
    canonical_prompt_intent: "Student identifies feedback as evidence after action.",
    allowed_choice_types: ["why"],
    sort_order: 15,
    fallback: scene(
      "H1_N15",
      "future_agent_lab",
      "cog9",
      "uncertain",
      "COG-9",
      "After I choose a route, what feedback should I check?",
      "Feedback tells the agent whether its action helped.",
      choices([
        ["A", "Whether the train arrived safely and on time.", "why"],
        ["B", "Whether the route was the fastest one.", "why"],
        ["C", "Whether the dashboard showed a green tick.", "why"],
      ]),
      "Feedback is evidence after the action.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "speed_only_feedback", C: "dashboard_without_outcome" },
      requires_followup: false,
      next_node_if_best: "H1_N16",
      next_node_if_partial: "H1_N16",
      next_node_if_retry: "H1_N15",
    },
  },
  {
    node_key: "H1_N16",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "ada",
    bloom_level: "Reflect",
    curriculum_concept: "Blueprint check",
    fixed_story_beat: "Ada checks whether the first blueprint draft includes a safety rule.",
    canonical_prompt_intent: "Student identifies the part of the blueprint that proves the agent has a guardrail.",
    allowed_choice_types: ["why"],
    sort_order: 16,
    fallback: scene(
      "H1_N16",
      "future_agent_lab",
      "ada",
      "encouraging",
      "Professor Ada",
      "Your first blueprint draft is on the workbench. Which part proves the agent has a safety check?",
      "A safety check is a rule or permission that stops the agent acting too freely.",
      choices([
        ["A", "It asks a human before changing the main timetable.", "why"],
        ["B", "It can change routes automatically after one good test.", "why"],
        ["C", "It hides small timetable changes to avoid delays.", "why"],
      ]),
      "Look for the guardrail that prevents unsafe action.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "surface_agent", C: "hidden_action" },
      requires_followup: false,
      next_node_if_best: "H1_N17",
      next_node_if_partial: "H1_N17",
      next_node_if_retry: "H1_N16",
    },
  },
  {
    node_key: "H1_N17",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "cog9",
    bloom_level: "Analyze",
    curriculum_concept: "Tool permissions",
    fixed_story_beat: "COG-9 asks which tools the Station Helper Agent is allowed to use by itself.",
    canonical_prompt_intent: "Student limits tools to safe reading and recommendation actions.",
    allowed_choice_types: ["backpack"],
    sort_order: 17,
    fallback: scene(
      "H1_N17",
      "future_agent_lab",
      "cog9",
      "uncertain",
      "COG-9",
      "Tool permissions needed. Which tools may the Station Helper Agent use without asking a human first?",
      "Tool permissions say what an agent can do on its own.",
      choices([
        ["A", "Read the Data Slate and suggest a route.", "backpack"],
        ["B", "Rewrite every timetable immediately.", "backpack"],
        ["C", "Delete records that make routes slower.", "backpack"],
      ]),
      "Safe tools let the agent inspect and recommend before it changes the city.",
      { required_item_slug: "data_slate", allowed_item_slugs: ["data_slate", "agent_blueprint"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "too_much_permission", C: "remove_evidence" },
      requires_followup: false,
      next_node_if_best: "H1_N18",
      next_node_if_partial: "H1_N18",
      next_node_if_retry: "H1_N17",
    },
  },
  {
    node_key: "H1_N18",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "ada",
    bloom_level: "Understand",
    curriculum_concept: "Useful memory",
    fixed_story_beat: "Ada asks what the agent should remember after each route choice.",
    canonical_prompt_intent: "Student chooses memory that supports later route improvement.",
    allowed_choice_types: ["evidence"],
    sort_order: 18,
    fallback: scene(
      "H1_N18",
      "future_agent_lab",
      "ada",
      "thinking",
      "Professor Ada",
      "The Station Helper Agent can remember one thing after each test route. What memory is useful?",
      "Useful memory helps the agent improve the next decision.",
      choices([
        ["A", "The chosen route and whether the train arrived safely.", "evidence"],
        ["B", "The route with the shortest travel time.", "evidence"],
        ["C", "Only the last passenger complaint.", "evidence"],
      ]),
      "Memory should connect an action to its result.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "speed_only_memory", C: "complaint_only_memory" },
      requires_followup: false,
      next_node_if_best: "H1_N19",
      next_node_if_partial: "H1_N19",
      next_node_if_retry: "H1_N18",
    },
  },
  {
    node_key: "H1_N19",
    room_slug: "future_mayorhall",
    room_title: ROOM_TITLES.future_mayorhall,
    character: "nix",
    bloom_level: "Analyze",
    curriculum_concept: "Stakeholder trade-off",
    fixed_story_beat: "Nix tries to make the agent favour only the loudest passengers.",
    canonical_prompt_intent: "Student balances passenger need, cargo safety, and power constraints.",
    allowed_choice_types: ["why"],
    sort_order: 19,
    fallback: scene(
      "H1_N19",
      "future_mayorhall",
      "nix",
      "mischievous",
      "Nix",
      "What if the agent always helps whoever shouts loudest? Very efficient, very dramatic.",
      "A helpful agent should not ignore quieter constraints.",
      choices([
        ["A", "Balance passenger need, cargo safety, and power limits.", "why"],
        ["B", "Only help the loudest passenger.", "why"],
        ["C", "Only help trains that are already delayed.", "why"],
      ]),
      "A good goal includes the important constraints, not just one loud signal.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "loudest_signal_bias", C: "delay_only_priority" },
      requires_followup: true,
      next_node_if_best: "H1_N20",
      next_node_if_partial: "H1_N20",
      next_node_if_retry: "H1_N19",
    },
  },
  {
    node_key: "H1_N20",
    room_slug: "future_trainstation",
    room_title: ROOM_TITLES.future_trainstation,
    character: "ada",
    bloom_level: "Apply",
    curriculum_concept: "Safe test run",
    fixed_story_beat: "Ada asks how to test the Station Helper Agent before it controls every train.",
    canonical_prompt_intent: "Student chooses a limited test instead of a full-city deployment.",
    allowed_choice_types: ["action"],
    sort_order: 20,
    fallback: scene(
      "H1_N20",
      "future_trainstation",
      "ada",
      "warning",
      "Professor Ada",
      "The agent is ready for a test. What is the safest first test?",
      "Test a system in a small way before trusting it with everything.",
      choices([
        ["A", "Run it on one low-risk route and compare the result.", "action"],
        ["B", "Let it control every train at once.", "action"],
        ["C", "Test it only on a perfect route with no fragile cargo.", "action"],
      ]),
      "A safe test limits the effect if the rule is wrong.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "unsafe_rollout", C: "perfect_case_only" },
      requires_followup: false,
      next_node_if_best: "H1_N21",
      next_node_if_partial: "H1_N21",
      next_node_if_retry: "H1_N20",
    },
  },
  {
    node_key: "H1_N21",
    room_slug: "future_trainstation",
    room_title: ROOM_TITLES.future_trainstation,
    character: "cog9",
    bloom_level: "Analyze",
    curriculum_concept: "Debugging evidence",
    fixed_story_beat: "The test route nearly works, but one fragile cargo train is sent too fast.",
    canonical_prompt_intent: "Student compares expected and actual output to debug a rule.",
    allowed_choice_types: ["evidence"],
    sort_order: 21,
    fallback: scene(
      "H1_N21",
      "future_trainstation",
      "cog9",
      "uncertain",
      "COG-9",
      "Test result: most trains are safe, but one fragile cargo train still took the fast track. What should we inspect?",
      "Debugging means comparing what should happen with what actually happened.",
      choices([
        ["A", "Compare the expected route with the actual route for that cargo.", "evidence"],
        ["B", "Check only whether the driver followed instructions.", "evidence"],
        ["C", "Ignore it because the average result was successful.", "evidence"],
      ]),
      "Find the mismatch between the rule and the output.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "driver_only_debugging", C: "ignore_edge_case" },
      requires_followup: false,
      next_node_if_best: "H1_N22",
      next_node_if_partial: "H1_N22",
      next_node_if_retry: "H1_N21",
    },
  },
  {
    node_key: "H1_N22",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "ada",
    bloom_level: "Create",
    curriculum_concept: "Rule revision",
    fixed_story_beat: "Ada asks the student to revise the route rule using the failed test.",
    canonical_prompt_intent: "Student updates the rule to include fragile cargo and power level.",
    allowed_choice_types: ["autocomplete_finish"],
    sort_order: 22,
    fallback: scene(
      "H1_N22",
      "future_agent_lab",
      "ada",
      "encouraging",
      "Professor Ada",
      "Revise the rule: If cargo is fragile and power is low, then...",
      "A debugged rule should fix the exact failure from the test.",
      choices([
        ["A", "choose the safe backup track even if it is slower.", "autocomplete_finish"],
        ["B", "choose the fastest track to save time.", "autocomplete_finish"],
        ["C", "remove fragile cargo from the data.", "autocomplete_finish"],
      ]),
      "The new action should handle the failed fragile-cargo case.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "speed_over_safety", C: "remove_evidence" },
      requires_followup: true,
      next_node_if_best: "H1_N23",
      next_node_if_partial: "H1_N23",
      next_node_if_retry: "H1_N22",
    },
  },
  {
    node_key: "H1_N23",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "cog9",
    bloom_level: "Reflect",
    curriculum_concept: "Explain a decision",
    fixed_story_beat: "COG-9 asks the student to explain why the final rule is safer.",
    canonical_prompt_intent: "Student explains that constraints are checked before speed.",
    allowed_choice_types: ["why"],
    sort_order: 23,
    fallback: scene(
      "H1_N23",
      "future_agent_lab",
      "cog9",
      "excited",
      "COG-9",
      "Explain my final rule so I can add it to the Agent Builder Passport. Why is it safer?",
      "A strong explanation says what evidence or constraint changed the action.",
      choices([
        ["A", "Because it checks power and cargo before choosing speed.", "why"],
        ["B", "Because it always chooses the slower route when there is risk.", "why"],
        ["C", "Because the agent guessed with confidence.", "why"],
      ]),
      "Mention the inputs and constraints that made the action safer.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "always_slow", C: "confidence_without_evidence" },
      requires_followup: false,
      next_node_if_best: "H1_N24",
      next_node_if_partial: "H1_N24",
      next_node_if_retry: "H1_N23",
    },
  },
  {
    node_key: "H1_N24",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "ada",
    bloom_level: "Reflect",
    curriculum_concept: "Mission reflection",
    fixed_story_beat: "Ada confirms the Station Helper Agent and prepares the Agent Builder Passport.",
    canonical_prompt_intent: "Student identifies what they built and learned.",
    allowed_choice_types: ["why"],
    sort_order: 24,
    fallback: scene(
      "H1_N24",
      "future_agent_lab",
      "ada",
      "encouraging",
      "Professor Ada",
      "Your Station Helper Agent is ready. What should your passport say you built?",
      "You built an agent with a goal, inputs, tools, rules, safety checks, and feedback.",
      choices([
        ["A", "An agent that chooses safe train routes using data, rules, and a human check.", "why"],
        ["B", "A chatbot that can say anything to anyone.", "why"],
        ["C", "An automatic route button that prioritises speed.", "why"],
      ]),
      "The passport should show the agent you assembled, not just a score.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "open_chat_confusion", C: "speed_button_agent" },
      requires_followup: false,
      next_node_if_best: "COMPLETE",
      next_node_if_partial: "COMPLETE",
      next_node_if_retry: "H1_N24",
    },
  },
];

export const NODE_BY_KEY = Object.fromEntries(EPISODE_ONE_NODES.map((node) => [node.node_key, node])) as Record<
  string,
  StoryNode
>;

export const FIRST_NODE_KEY = "H1_N01";
