import type { ScenePayload, StoryNode } from "./types";

const baseSafety = {
  contains_open_chat: false,
  asks_personal_data: false,
  out_of_sandbox: false,
};

const baseAccessibility = {
  reading_level: "standard" as const,
  max_words_ok: true,
};

function scene(
  node_key: string,
  room_slug: string,
  character: ScenePayload["character"],
  character_state: ScenePayload["character_state"],
  speaker_name: string,
  text: string,
  read_again_text: string,
  choices: ScenePayload["choices"],
  clue?: string,
  backpack?: ScenePayload["backpack_prompt"],
): ScenePayload {
  return {
    scene_id: `fallback-${node_key}`,
    node_key,
    room_slug,
    language: "en",
    character,
    character_state,
    dialogue: { speaker_name, text, read_again_text },
    choices,
    backpack_prompt: backpack,
    clue: clue ? { available: true, text: clue } : { available: false, text: "" },
    consequence_preview: { show_after_choice: true, tone: "debug" },
    accessibility: baseAccessibility,
    safety_flags: baseSafety,
  };
}

function choices(items: Array<[ScenePayload["choices"][number]["id"], string, ScenePayload["choices"][number]["choice_type"]]>): ScenePayload["choices"] {
  return items.map(([id, text, choice_type]) => ({ id, text, choice_type }));
}

export const ROOM_SEQUENCE = [
  "future_trainstation",
  "future_market",
  "future_reactorcore",
  "1800_trainstation",
  "1800_signal_telegraph_office",
  "future_mayorhall",
  "future_agent_lab",
] as const;

export const ROOM_TITLES: Record<string, string> = {
  future_trainstation: "Future Train Station",
  future_market: "Future Market",
  future_reactorcore: "Future Reactor Core",
  "1800_trainstation": "1888 Train Station",
  "1800_signal_telegraph_office": "1888 Telegraph Office",
  future_mayorhall: "Future Town Hall",
  future_agent_lab: "Future Agent Lab",
};

export const CHARACTERS = ["ada", "cog9", "nix"] as const;
export const BACKPACK_ITEMS = ["logic_lens", "data_slate", "debug_wrench", "prompt_card", "agent_blueprint", "safety_seal"] as const;
export const BADGES = ["route_badge", "data_badge", "debug_badge", "agent_badge"] as const;

export const CHARACTER_PROFILES = {
  ada:
    "Professor Ada is calm, curious, and Socratic. She never gives away the answer; she asks students to name evidence, compare causes, and explain why a safer rule works.",
  cog9:
    "COG-9 is a literal station helper robot. He is earnest, slightly anxious, and wants exact signals before acting. He speaks in concrete station observations, not abstract teacher language.",
  nix:
    "Nix is a mischievous signal glitch. Nix tempts the player toward speed, shortcuts, and dramatic buttons. Nix does not politely ask what to ask; Nix creates pressure the player must resist.",
} as const;

export const EPISODE_ONE_NODES: StoryNode[] = [
  {
    node_key: "H1_N01",
    room_slug: "future_trainstation",
    room_title: ROOM_TITLES.future_trainstation,
    character: "cog9",
    bloom_level: "Remember",
    curriculum_concept: "Explore before solving",
    fixed_story_beat: "COG-9 appears for the first time, introduces himself as the station helper robot, and shows that the main clock, platform sign, and dispatch log disagree. The student explores evidence before touching any controls.",
    canonical_prompt_intent: "Student chooses to compare station evidence before acting. Do not name any backend system in this opening beat.",
    allowed_choice_types: ["action"],
    scripted: true,
    sort_order: 1,
    fallback: scene(
      "H1_N01",
      "future_trainstation",
      "cog9",
      "uncertain",
      "COG-9",
      "Hello. I am COG-9, the station helper robot. My platform sign flashed GO at 08:05, but the main clock still says 08:04 and the dispatch log says three trains already left. One minute is missing.",
      "COG-9 has three station clues: platform sign, main clock, and dispatch log. They disagree by one minute.",
      choices([
        ["A", "Follow the green platform sign because it controls dispatch.", "action"],
        ["B", "Compare the sign, clock, and dispatch log before moving another train.", "action"],
        ["C", "Follow the dispatch log because it records real trains.", "action"],
      ]),
      "The safest first move is to compare the station clues that disagree.",
    ),
    evaluation_key: {
      best_choice_ids: ["B"],
      partial_choice_ids: [],
      misconception_map: { A: "unreliable_evidence", C: "partial_time_evidence" },
      requires_followup: false,
      next_node_if_best: "H1_N02",
      next_node_if_partial: "H1_N02",
      next_node_if_retry: "H1_N01",
    },
  },
  {
    node_key: "H1_N02",
    room_slug: "future_trainstation",
    room_title: ROOM_TITLES.future_trainstation,
    character: "cog9",
    bloom_level: "Remember",
    curriculum_concept: "Inputs",
    fixed_story_beat: "Ada turns the evidence into the first AI idea: COG-9 needs useful inputs before suggesting any safe train movement.",
    canonical_prompt_intent: "Student chooses useful input data for COG-9's first station check.",
    allowed_choice_types: ["evidence"],
    scripted: true,
    sort_order: 2,
    fallback: scene(
      "H1_N02",
      "future_trainstation",
      "ada",
      "thinking",
      "Professor Ada",
      "Ada kneels beside the route board. COG-9 can help, but only if we feed him the right station inputs. Which set would actually explain the missing minute?",
      "Inputs are the evidence a system reads before it chooses an action.",
      choices([
        ["A", "Platform sign time, dispatch log time, and passenger queue size.", "evidence"],
        ["B", "Main clock time, platform sign time, and cargo manifest.", "evidence"],
        ["C", "Main clock time, platform sign time, and dispatch log time.", "evidence"],
      ]),
      "Useful inputs are the clues that could explain the one-minute mismatch.",
    ),
    evaluation_key: {
      best_choice_ids: ["C"],
      partial_choice_ids: [],
      misconception_map: { A: "partial_time_evidence", B: "mixed_context_inputs" },
      requires_followup: false,
      next_node_if_best: "H1_N03",
      next_node_if_partial: "H1_N03",
      next_node_if_retry: "H1_N02",
    },
  },
  {
    node_key: "H1_N03",
    room_slug: "future_trainstation",
    room_title: ROOM_TITLES.future_trainstation,
    character: "nix",
    bloom_level: "Understand",
    curriculum_concept: "Ask before acting",
    fixed_story_beat: "Nix introduces themself as a signal glitch from the station screens, then tempts the student to dispatch trains before asking what could go wrong.",
    canonical_prompt_intent: "Student asks a useful safety question before continuing. Introduce Nix before any temptation or challenge.",
    allowed_choice_types: ["ask_question"],
    scripted: true,
    sort_order: 3,
    fallback: scene(
      "H1_N03",
      "future_trainstation",
      "nix",
      "mischievous",
      "Nix",
      "I'm Nix, a signal glitch from the station screens. That DISPATCH button is glowing beautifully. Press it now and the city looks fixed. Probably.",
      "Nix is pushing for speed. A systems detective names the risk before acting.",
      choices([
        ["A", "What could go wrong if we dispatch while the clocks disagree?", "ask_question"],
        ["B", "How fast can we make the next train leave?", "ask_question"],
        ["C", "Can we hide the wrong minute until the station gets quiet?", "ask_question"],
      ]),
      "A good question checks the risk created by the mismatch.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "irrelevant_feature", C: "unsafe_shortcut" },
      requires_followup: true,
      next_node_if_best: "H1_N04",
      next_node_if_partial: "H1_N04",
      next_node_if_retry: "H1_N03",
    },
  },
  {
    node_key: "H1_N04",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "ada",
    bloom_level: "Understand",
    curriculum_concept: "Clean data",
    fixed_story_beat: "Ada sends the student to the market to gather clean cargo data.",
    canonical_prompt_intent: "Student distinguishes clean evidence from noisy observations.",
    allowed_choice_types: ["evidence"],
    scripted: true,
    sort_order: 4,
    fallback: scene(
      "H1_N04",
      "future_market",
      "ada",
      "thinking",
      "Professor Ada",
      "At the market platform, three urgent crates roll in: frozen medicine, glass panels, and heavy repair parts. Which record should COG-9 read before choosing a route?",
      "The route rule needs cargo evidence because different cargo can need different tracks.",
      choices([
        ["A", "The delivery priority list showing which customer is waiting.", "evidence"],
        ["B", "The cargo manifest showing frozen, fragile, or heavy crates.", "evidence"],
        ["C", "The scanner photo showing crate shape and label colour.", "evidence"],
      ]),
      "Choose evidence that can change the route decision.",
    ),
    evaluation_key: {
      best_choice_ids: ["B"],
      partial_choice_ids: [],
      misconception_map: { A: "priority_over_evidence", C: "surface_detail" },
      requires_followup: false,
      next_node_if_best: "H1_N05",
      next_node_if_partial: "H1_N05",
      next_node_if_retry: "H1_N04",
    },
  },
  {
    node_key: "H1_N05",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "cog9",
    bloom_level: "Apply",
    curriculum_concept: "Input versus output",
    fixed_story_beat: "COG-9 separates the cargo input from the route output.",
    canonical_prompt_intent: "Student identifies output as the system decision.",
    allowed_choice_types: ["why"],
    scripted: true,
    sort_order: 5,
    fallback: scene(
      "H1_N05",
      "future_market",
      "cog9",
      "uncertain",
      "COG-9",
      "COG-9's screen splits into three boxes: cargo facts, warning notes, and route command. Which box is the output he creates?",
      "The output is the decision COG-9 produces after reading evidence.",
      choices([
        ["A", "The cargo facts COG-9 reads before deciding.", "why"],
        ["B", "The warning note COG-9 shows beside the manifest.", "why"],
        ["C", "The route command COG-9 recommends for the train.", "why"],
      ]),
      "Look for the thing the system decides, not the evidence it reads.",
    ),
    evaluation_key: {
      best_choice_ids: ["C"],
      partial_choice_ids: ["A"],
      misconception_map: { A: "input_as_output", B: "display_as_output" },
      requires_followup: false,
      next_node_if_best: "H1_N06",
      next_node_if_partial: "H1_N06",
      next_node_if_retry: "H1_N05",
    },
  },
  {
    node_key: "H1_N06",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "ada",
    bloom_level: "Apply",
    curriculum_concept: "Backpack data tool",
    fixed_story_beat: "The student uses the Data Slate to carry clean inputs back to the station.",
    canonical_prompt_intent: "Student uses a backpack item with a reason.",
    allowed_choice_types: ["backpack"],
    required_backpack_item: "data_slate",
    scripted: true,
    sort_order: 6,
    fallback: scene(
      "H1_N06",
      "future_market",
      "ada",
      "encouraging",
      "Professor Ada",
      "The loaders hand you clean cargo scans and a battery reading. Which backpack item should carry those inputs back to COG-9 without mixing them up?",
      "The Data Slate stores clean input evidence for the route rule.",
      choices([
        ["A", "Use the Safety Seal to lock the record once Ada has checked it.", "backpack"],
        ["B", "Use the Data Slate to store the cargo scans and battery reading.", "backpack"],
        ["C", "Use the Prompt Card to write a clearer label for each crate.", "backpack"],
      ]),
      "The right item should match the job: storing useful data.",
      { required_item_slug: "data_slate", allowed_item_slugs: ["data_slate", "safety_seal"] },
    ),
    evaluation_key: {
      best_choice_ids: ["B"],
      partial_choice_ids: [],
      misconception_map: { A: "tool_without_purpose", C: "memory_over_evidence" },
      requires_followup: false,
      next_node_if_best: "H1_N07",
      next_node_if_partial: "H1_N07",
      next_node_if_retry: "H1_N06",
    },
  },
  {
    node_key: "H1_N07",
    room_slug: "future_reactorcore",
    room_title: ROOM_TITLES.future_reactorcore,
    character: "cog9",
    bloom_level: "Analyze",
    curriculum_concept: "Loop stopping condition",
    fixed_story_beat: "The reactor keeps draining power because a loop has no safe stop.",
    canonical_prompt_intent: "Student chooses a stopping condition for a loop.",
    allowed_choice_types: ["action"],
    scripted: true,
    sort_order: 7,
    fallback: scene(
      "H1_N07",
      "future_reactorcore",
      "cog9",
      "warning",
      "COG-9",
      "The reactor charger is stuck chanting: send power, send power, send power. The station battery is climbing, but the command keeps looping. What condition should stop it?",
      "A loop needs a condition that tells it when the job is done.",
      choices([
        ["A", "Stop when the station battery is full enough.", "action"],
        ["B", "Keep charging while anyone is worried about delays.", "action"],
        ["C", "Stop after five repeats even if the battery is still low.", "action"],
      ]),
      "A safe loop stops when the goal condition is met.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "runaway_loop", C: "irrelevant_condition" },
      requires_followup: true,
      next_node_if_best: "H1_N08",
      next_node_if_partial: "H1_N08",
      next_node_if_retry: "H1_N07",
    },
  },
  {
    node_key: "H1_N08",
    room_slug: "future_reactorcore",
    room_title: ROOM_TITLES.future_reactorcore,
    character: "ada",
    bloom_level: "Analyze",
    curriculum_concept: "Debugging with a tool",
    fixed_story_beat: "The student uses the Debug Wrench to inspect the looping rule.",
    canonical_prompt_intent: "Student picks the debug action that checks the condition.",
    allowed_choice_types: ["backpack"],
    required_backpack_item: "debug_wrench",
    scripted: true,
    sort_order: 8,
    fallback: scene(
      "H1_N08",
      "future_reactorcore",
      "ada",
      "thinking",
      "Professor Ada",
      "The Debug Wrench clicks open the charger rule. Which part should it inspect before COG-9 sends more power?",
      "Debugging means inspecting the rule that caused the behaviour you can see.",
      choices([
        ["A", "Whether the charger checks the battery before repeating.", "backpack"],
        ["B", "Whether the charger can repeat the command faster.", "backpack"],
        ["C", "Whether the train timetable changed while charging.", "backpack"],
      ]),
      "Inspect the condition that controls the loop.",
      { required_item_slug: "debug_wrench", allowed_item_slugs: ["debug_wrench"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "surface_detail", C: "person_not_rule" },
      requires_followup: false,
      next_node_if_best: "H1_N09",
      next_node_if_partial: "H1_N09",
      next_node_if_retry: "H1_N08",
    },
  },
  {
    node_key: "H1_N09",
    room_slug: "1800_trainstation",
    room_title: ROOM_TITLES["1800_trainstation"],
    character: "ada",
    bloom_level: "Apply",
    curriculum_concept: "Sequencing",
    fixed_story_beat: "The time signal jumps to 1888, where station rules must be simpler and ordered.",
    canonical_prompt_intent: "Student sequences route instructions in plain steps.",
    allowed_choice_types: ["autocomplete_finish"],
    scripted: true,
    sort_order: 9,
    fallback: scene(
      "H1_N09",
      "1800_trainstation",
      "ada",
      "encouraging",
      "Professor Ada",
      "1888 station workers need simple steps. Finish the route instruction: First check power, then...",
      "A sequence puts steps in the order someone can follow.",
      choices([
        ["A", "check cargo type, then choose the safe track.", "autocomplete_finish"],
        ["B", "choose any track, then check the inputs later.", "autocomplete_finish"],
        ["C", "choose the shortest track after counting passengers.", "autocomplete_finish"],
      ]),
      "Good instructions put checks before action.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "act_before_checking", C: "guessing" },
      requires_followup: false,
      next_node_if_best: "H1_N10",
      next_node_if_partial: "H1_N10",
      next_node_if_retry: "H1_N09",
    },
  },
  {
    node_key: "H1_N10",
    room_slug: "1800_signal_telegraph_office",
    room_title: ROOM_TITLES["1800_signal_telegraph_office"],
    character: "cog9",
    bloom_level: "Understand",
    curriculum_concept: "Clear instructions",
    fixed_story_beat: "The telegraph message is ambiguous and must be rewritten.",
    canonical_prompt_intent: "Student chooses a clear instruction/prompt.",
    allowed_choice_types: ["autocomplete_finish"],
    required_backpack_item: "prompt_card",
    scripted: true,
    sort_order: 10,
    fallback: scene(
      "H1_N10",
      "1800_signal_telegraph_office",
      "cog9",
      "uncertain",
      "COG-9",
      "The telegraph says: 'Send train soon.' Use the Prompt Card. Which version is clearer?",
      "A clear instruction says what to do and when to do it.",
      choices([
        ["A", "If power is safe, send the cargo train to Track B before noon.", "autocomplete_finish"],
        ["B", "Send the cargo train to Track B when the platform looks ready.", "autocomplete_finish"],
        ["C", "Send the train before noon if someone confirms the route.", "autocomplete_finish"],
      ]),
      "Clear prompts reduce guessing.",
      { required_item_slug: "prompt_card", allowed_item_slugs: ["prompt_card"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "ambiguous_condition", C: "missing_specifics" },
      requires_followup: true,
      next_node_if_best: "H1_N11",
      next_node_if_partial: "H1_N11",
      next_node_if_retry: "H1_N10",
    },
  },
  {
    node_key: "H1_N11",
    room_slug: "future_mayorhall",
    room_title: ROOM_TITLES.future_mayorhall,
    character: "nix",
    bloom_level: "Evaluate",
    curriculum_concept: "Trade-offs",
    fixed_story_beat: "Back in TimeCity, Nix introduces Ada's Station Helper Agent plan as a helper that reads inputs and suggests routes, then argues it should optimise only for speed.",
    canonical_prompt_intent: "Student recognises that speed is not the only goal. Introduce Station Helper Agent before asking about it.",
    allowed_choice_types: ["why"],
    scripted: true,
    sort_order: 11,
    fallback: scene(
      "H1_N11",
      "future_mayorhall",
      "nix",
      "mischievous",
      "Nix",
      "The mayor is pacing outside Town Hall. Ada's Station Helper Agent plan would read station evidence and recommend routes for a human to approve. I say make it pick the fastest route every time. Dramatic. Simple. Why should Ada push back?",
      "Optimising one thing can create problems if constraints are ignored.",
      choices([
        ["A", "Because cargo safety, power, and passengers still matter.", "why"],
        ["B", "Because the fastest route should be used only at night.", "why"],
        ["C", "Because one speed goal can replace every safety rule.", "why"],
      ]),
      "Good agents need goals and constraints.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "opposite_extreme", C: "no_goal" },
      requires_followup: false,
      next_node_if_best: "H1_N12",
      next_node_if_partial: "H1_N12",
      next_node_if_retry: "H1_N11",
    },
  },
  {
    node_key: "H1_N12",
    room_slug: "future_mayorhall",
    room_title: ROOM_TITLES.future_mayorhall,
    character: "ada",
    bloom_level: "Evaluate",
    curriculum_concept: "Safeguards",
    fixed_story_beat: "Ada asks for a safety guardrail before the station agent can control routes.",
    canonical_prompt_intent: "Student chooses a human review safeguard.",
    allowed_choice_types: ["backpack"],
    required_backpack_item: "safety_seal",
    scripted: true,
    sort_order: 12,
    fallback: scene(
      "H1_N12",
      "future_mayorhall",
      "ada",
      "thinking",
      "Professor Ada",
      "The mayor wants the agent connected to the live timetable. Ada slides the Safety Seal onto the table. Which safeguard should go in before any real timetable changes?",
      "A safeguard limits what an agent can do without human review.",
      choices([
        ["A", "Ask a human before changing the main timetable.", "backpack"],
        ["B", "Let the agent quietly change small delays without telling anyone.", "backpack"],
        ["C", "Let the agent remove constraints when the station is busy.", "backpack"],
      ]),
      "Safety checks keep powerful tools under review.",
      { required_item_slug: "safety_seal", allowed_item_slugs: ["safety_seal"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "hidden_action", C: "no_constraints" },
      requires_followup: false,
      next_node_if_best: "H1_N13",
      next_node_if_partial: "H1_N13",
      next_node_if_retry: "H1_N12",
    },
  },
  {
    node_key: "H1_N13",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "cog9",
    bloom_level: "Create",
    curriculum_concept: "Agent blueprint",
    fixed_story_beat: "The student starts assembling the Station Helper Agent.",
    canonical_prompt_intent: "Student picks the correct blueprint parts.",
    allowed_choice_types: ["backpack"],
    required_backpack_item: "agent_blueprint",
    scripted: true,
    sort_order: 13,
    fallback: scene(
      "H1_N13",
      "future_agent_lab",
      "cog9",
      "excited",
      "COG-9",
      "In the Agent Lab, COG-9 projects a blueprint over the route board. Nix keeps trying to scribble SPEED in every box. Which build would survive a real station test?",
      "An agent needs a goal, inputs, tools, rules, safeguards, and feedback.",
      choices([
        ["A", "Goal, inputs, speed target, and automatic timetable access.", "backpack"],
        ["B", "Goal, inputs, tools, rules, safety check, and feedback.", "backpack"],
        ["C", "Goal, output, speed target, and dashboard badge.", "backpack"],
      ]),
      "The blueprint should describe how the agent acts safely.",
      { required_item_slug: "agent_blueprint", allowed_item_slugs: ["agent_blueprint"] },
    ),
    evaluation_key: {
      best_choice_ids: ["B"],
      partial_choice_ids: [],
      misconception_map: { A: "missing_guardrail", C: "surface_agent" },
      requires_followup: false,
      next_node_if_best: "H1_N14",
      next_node_if_partial: "H1_N14",
      next_node_if_retry: "H1_N13",
    },
  },
  {
    node_key: "H1_N14",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "ada",
    bloom_level: "Create",
    curriculum_concept: "Agent rule",
    fixed_story_beat: "Ada asks the student to write the core if/then route rule.",
    canonical_prompt_intent: "Student completes a condition-action rule.",
    allowed_choice_types: ["autocomplete_finish"],
    scripted: true,
    sort_order: 14,
    fallback: scene(
      "H1_N14",
      "future_agent_lab",
      "ada",
      "encouraging",
      "Professor Ada",
      "The first route rule is glowing on the workbench. Complete it: If power is low and cargo is fragile, then...",
      "If/then rules connect conditions to safe actions.",
      choices([
        ["A", "send the train to the safe backup track.", "autocomplete_finish"],
        ["B", "send it to the fastest track anyway.", "autocomplete_finish"],
        ["C", "delete the cargo record.", "autocomplete_finish"],
      ]),
      "The action should match the condition.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "speed_over_safety", C: "remove_evidence" },
      requires_followup: true,
      next_node_if_best: "H1_N15",
      next_node_if_partial: "H1_N15",
      next_node_if_retry: "H1_N14",
    },
  },
  {
    node_key: "H1_N15",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "cog9",
    bloom_level: "Reflect",
    curriculum_concept: "Feedback loop",
    fixed_story_beat: "COG-9 asks how the agent should learn whether the route worked.",
    canonical_prompt_intent: "Student identifies feedback as evidence after action.",
    allowed_choice_types: ["why"],
    scripted: true,
    sort_order: 15,
    fallback: scene(
      "H1_N15",
      "future_agent_lab",
      "cog9",
      "uncertain",
      "COG-9",
      "COG-9 runs one tiny test train through the lab simulator. After I recommend a route, what feedback should I check?",
      "Feedback tells the agent whether its action helped.",
      choices([
        ["A", "Whether passenger complaints dropped fastest.", "why"],
        ["B", "Whether the train arrived safely, on time, with cargo intact.", "why"],
        ["C", "Whether the dashboard confidence score stayed high.", "why"],
      ]),
      "Feedback is evidence after the action.",
    ),
    evaluation_key: {
      best_choice_ids: ["B"],
      partial_choice_ids: [],
      misconception_map: { A: "speed_only_feedback", C: "dashboard_without_outcome" },
      requires_followup: false,
      next_node_if_best: "H1_N16",
      next_node_if_partial: "H1_N16",
      next_node_if_retry: "H1_N15",
    },
  },
  {
    node_key: "H1_N16",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "ada",
    bloom_level: "Reflect",
    curriculum_concept: "Blueprint check",
    fixed_story_beat: "Ada checks whether the first blueprint draft includes a safety rule.",
    canonical_prompt_intent: "Student identifies the part of the blueprint that proves the agent has a guardrail.",
    allowed_choice_types: ["why"],
    scripted: true,
    sort_order: 16,
    fallback: scene(
      "H1_N16",
      "future_agent_lab",
      "ada",
      "encouraging",
      "Professor Ada",
      "Your first blueprint draft hums like it wants to wake up. Which part proves the agent cannot change TimeCity by itself?",
      "A safety check is a rule or permission that stops the agent acting too freely.",
      choices([
        ["A", "It logs every automatic change after the timetable updates.", "why"],
        ["B", "It uses only low-risk routes during the first hour.", "why"],
        ["C", "It asks a human before changing the main timetable.", "why"],
      ]),
      "Look for the guardrail that prevents unsafe action.",
    ),
    evaluation_key: {
      best_choice_ids: ["C"],
      partial_choice_ids: [],
      misconception_map: { A: "hidden_action", B: "surface_agent" },
      requires_followup: false,
      next_node_if_best: "H1_N17",
      next_node_if_partial: "H1_N17",
      next_node_if_retry: "H1_N16",
    },
  },
  {
    node_key: "H1_N17",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "cog9",
    bloom_level: "Analyze",
    curriculum_concept: "Tool permissions",
    fixed_story_beat: "COG-9 asks which tools the Station Helper Agent is allowed to use by itself.",
    canonical_prompt_intent: "Student limits tools to safe reading and recommendation actions.",
    allowed_choice_types: ["backpack"],
    scripted: true,
    sort_order: 17,
    fallback: scene(
      "H1_N17",
      "future_agent_lab",
      "cog9",
      "uncertain",
      "COG-9",
      "The permissions panel flashes red. Which tools may the Station Helper Agent use without asking a human first?",
      "Tool permissions say what an agent can do on its own.",
      choices([
        ["A", "Read the Data Slate and suggest a route.", "backpack"],
        ["B", "Rewrite low-risk timetable rows during quiet hours.", "backpack"],
        ["C", "Hide cargo records that make the route slower.", "backpack"],
      ]),
      "Safe tools let the agent inspect and recommend before it changes the city.",
      { required_item_slug: "data_slate", allowed_item_slugs: ["data_slate", "agent_blueprint"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "too_much_permission", C: "remove_evidence" },
      requires_followup: false,
      next_node_if_best: "H1_N18",
      next_node_if_partial: "H1_N18",
      next_node_if_retry: "H1_N17",
    },
  },
  {
    node_key: "H1_N18",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "nix",
    bloom_level: "Understand",
    curriculum_concept: "Useful memory",
    fixed_story_beat: "Ada asks what the agent should remember after each route choice.",
    canonical_prompt_intent: "Student chooses memory that supports later route improvement.",
    allowed_choice_types: ["evidence"],
    scripted: true,
    sort_order: 18,
    fallback: scene(
      "H1_N18",
      "future_agent_lab",
      "ada",
      "thinking",
      "Professor Ada",
      "The test train returns from the simulator. The agent can remember one thing for next time. What memory is useful?",
      "Useful memory helps the agent improve the next decision.",
      choices([
        ["A", "The chosen route and whether the train arrived safely.", "evidence"],
        ["B", "The route with the shortest travel time.", "evidence"],
        ["C", "Only the last passenger complaint.", "evidence"],
      ]),
      "Memory should connect an action to its result.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "speed_only_memory", C: "complaint_only_memory" },
      requires_followup: false,
      next_node_if_best: "H1_N19",
      next_node_if_partial: "H1_N19",
      next_node_if_retry: "H1_N18",
    },
  },
  {
    node_key: "H1_N19",
    room_slug: "future_mayorhall",
    room_title: ROOM_TITLES.future_mayorhall,
    character: "nix",
    bloom_level: "Analyze",
    curriculum_concept: "Stakeholder trade-off",
    fixed_story_beat: "Nix tries to make the agent favour only the loudest passengers.",
    canonical_prompt_intent: "Student balances passenger need, cargo safety, and power constraints.",
    allowed_choice_types: ["why"],
    scripted: true,
    sort_order: 19,
    fallback: scene(
      "H1_N19",
      "future_mayorhall",
      "nix",
      "mischievous",
      "Nix",
      "Passengers are crowding the mayor's steps. What if the agent always helps whoever shouts loudest? Very efficient, very dramatic.",
      "A helpful agent should not ignore quieter constraints.",
      choices([
        ["A", "Balance passenger need, cargo safety, and power limits.", "why"],
        ["B", "Only help the loudest passenger.", "why"],
        ["C", "Only help trains that are already delayed.", "why"],
      ]),
      "A good goal includes the important constraints, not just one loud signal.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "loudest_signal_bias", C: "delay_only_priority" },
      requires_followup: true,
      next_node_if_best: "H1_N20",
      next_node_if_partial: "H1_N20",
      next_node_if_retry: "H1_N19",
    },
  },
  {
    node_key: "H1_N20",
    room_slug: "future_trainstation",
    room_title: ROOM_TITLES.future_trainstation,
    character: "ada",
    bloom_level: "Apply",
    curriculum_concept: "Safe test run",
    fixed_story_beat: "Nix pressures the student to launch the Station Helper Agent everywhere, forcing a limited-test decision.",
    canonical_prompt_intent: "Student chooses a limited test instead of a full-city deployment.",
    allowed_choice_types: ["action"],
    scripted: true,
    sort_order: 20,
    fallback: scene(
      "H1_N20",
      "future_trainstation",
      "nix",
      "mischievous",
      "Nix",
      "The station lights are back. The mayor's city-wide switch is right there. I could press it with one tiny glitch-finger. How do we test before I get bored?",
      "Test a system in a small way before trusting it with everything.",
      choices([
        ["A", "Let it control every train for one minute.", "action"],
        ["B", "Test only a perfect route with no fragile cargo.", "action"],
        ["C", "Run it on one low-risk route and compare the result.", "action"],
      ]),
      "A safe test limits the effect if the rule is wrong.",
    ),
    evaluation_key: {
      best_choice_ids: ["C"],
      partial_choice_ids: [],
      misconception_map: { A: "unsafe_rollout", B: "perfect_case_only" },
      requires_followup: false,
      next_node_if_best: "H1_N21",
      next_node_if_partial: "H1_N21",
      next_node_if_retry: "H1_N20",
    },
  },
  {
    node_key: "H1_N21",
    room_slug: "future_trainstation",
    room_title: ROOM_TITLES.future_trainstation,
    character: "cog9",
    bloom_level: "Analyze",
    curriculum_concept: "Debugging evidence",
    fixed_story_beat: "The test route nearly works, but one fragile cargo train is sent too fast.",
    canonical_prompt_intent: "Student compares expected and actual output to debug a rule.",
    allowed_choice_types: ["evidence"],
    scripted: true,
    sort_order: 21,
    fallback: scene(
      "H1_N21",
      "future_trainstation",
      "cog9",
      "uncertain",
      "COG-9",
      "The limited test nearly works. One fragile glass shipment still takes the fast track and rattles hard through the turn. What should we inspect?",
      "Debugging means comparing what should happen with what actually happened.",
      choices([
        ["A", "Compare the expected route with the actual route for that cargo.", "evidence"],
        ["B", "Check only whether the driver followed instructions.", "evidence"],
        ["C", "Ignore it because the average result was successful.", "evidence"],
      ]),
      "Find the mismatch between the rule and the output.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "driver_only_debugging", C: "ignore_edge_case" },
      requires_followup: false,
      next_node_if_best: "H1_N22",
      next_node_if_partial: "H1_N22",
      next_node_if_retry: "H1_N21",
    },
  },
  {
    node_key: "H1_N22",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "ada",
    bloom_level: "Create",
    curriculum_concept: "Rule revision",
    fixed_story_beat: "Ada asks the student to revise the route rule using the failed test.",
    canonical_prompt_intent: "Student updates the rule to include fragile cargo and power level.",
    allowed_choice_types: ["autocomplete_finish"],
    scripted: true,
    sort_order: 22,
    fallback: scene(
      "H1_N22",
      "future_agent_lab",
      "ada",
      "encouraging",
      "Professor Ada",
      "The failed test tells us exactly where the rule broke. Revise it: If cargo is fragile and power is low, then...",
      "A debugged rule should fix the exact failure from the test.",
      choices([
        ["A", "choose the safe backup track even if it is slower.", "autocomplete_finish"],
        ["B", "choose the fastest track to save time.", "autocomplete_finish"],
        ["C", "remove fragile cargo from the data.", "autocomplete_finish"],
      ]),
      "The new action should handle the failed fragile-cargo case.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "speed_over_safety", C: "remove_evidence" },
      requires_followup: true,
      next_node_if_best: "H1_N23",
      next_node_if_partial: "H1_N23",
      next_node_if_retry: "H1_N22",
    },
  },
  {
    node_key: "H1_N23",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "cog9",
    bloom_level: "Reflect",
    curriculum_concept: "Explain a decision",
    fixed_story_beat: "COG-9 asks the student to explain why the final rule is safer.",
    canonical_prompt_intent: "Student explains that constraints are checked before speed.",
    allowed_choice_types: ["why"],
    scripted: true,
    sort_order: 23,
    fallback: scene(
      "H1_N23",
      "future_agent_lab",
      "cog9",
      "excited",
      "COG-9",
      "COG-9 holds up the Agent Builder Passport stamp. Explain the final rule before I stamp it. Why is it safer?",
      "A strong explanation says what evidence or constraint changed the action.",
      choices([
        ["A", "Because it checks power and cargo before choosing speed.", "why"],
        ["B", "Because it always uses the backup track for fragile cargo.", "why"],
        ["C", "Because it chooses the route with the highest confidence score.", "why"],
      ]),
      "Mention the inputs and constraints that made the action safer.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "always_slow", C: "confidence_without_evidence" },
      requires_followup: false,
      next_node_if_best: "H1_N24",
      next_node_if_partial: "H1_N24",
      next_node_if_retry: "H1_N23",
    },
  },
  {
    node_key: "H1_N24",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "ada",
    bloom_level: "Reflect",
    curriculum_concept: "Mission reflection",
    fixed_story_beat: "Ada confirms the Station Helper Agent and prepares the Agent Builder Passport.",
    canonical_prompt_intent: "Student identifies what they built and learned.",
    allowed_choice_types: ["why"],
    scripted: true,
    sort_order: 24,
    fallback: scene(
      "H1_N24",
      "future_agent_lab",
      "ada",
      "encouraging",
      "Professor Ada",
      "The clocks click back into sync. A night-market train cheers from the platform, COG-9 stops shaking, and Nix pretends this was all planned. What should your passport say you built?",
      "You restored the missing minute by building an agent with a goal, inputs, tools, rules, safety checks, and feedback.",
      choices([
        ["A", "An automatic timetable fixer that learns after one good test.", "why"],
        ["B", "An agent that recommends safe train routes using evidence, rules, and a human check.", "why"],
        ["C", "A dashboard that shows the fastest route and hides risky records.", "why"],
      ]),
      "The passport should show the agent you assembled, not just a score.",
    ),
    evaluation_key: {
      best_choice_ids: ["B"],
      partial_choice_ids: [],
      misconception_map: { A: "too_much_permission", C: "speed_button_agent" },
      requires_followup: false,
      next_node_if_best: "COMPLETE",
      next_node_if_partial: "COMPLETE",
      next_node_if_retry: "H1_N24",
    },
  },
];

export const NODE_BY_KEY = Object.fromEntries(EPISODE_ONE_NODES.map((node) => [node.node_key, node])) as Record<
  string,
  StoryNode
>;

export const FIRST_NODE_KEY = "H1_N01";
