import type { ScenePayload, StoryNode } from "./types";

const baseSafety = {
  contains_open_chat: false,
  asks_personal_data: false,
  out_of_sandbox: false,
};

const baseAccessibility = {
  reading_level: "standard" as const,
  max_words_ok: true,
};

function scene(
  node_key: string,
  room_slug: string,
  character: ScenePayload["character"],
  character_state: ScenePayload["character_state"],
  speaker_name: string,
  text: string,
  read_again_text: string,
  choices: ScenePayload["choices"],
  clue?: string,
  backpack?: ScenePayload["backpack_prompt"],
): ScenePayload {
  return {
    scene_id: `fallback-${node_key}`,
    node_key,
    room_slug,
    language: "en",
    character,
    character_state,
    dialogue: { speaker_name, text, read_again_text },
    choices,
    backpack_prompt: backpack,
    clue: clue ? { available: true, text: clue } : { available: false, text: "" },
    consequence_preview: { show_after_choice: true, tone: "debug" },
    accessibility: baseAccessibility,
    safety_flags: baseSafety,
  };
}

export const ROOM_SEQUENCE = ["future_agent_lab", "future_market", "future_agent_lab_return"] as const;

export const ROOM_TITLES: Record<string, string> = {
  future_agent_lab: "Future Agent Lab",
  future_market: "Future Market",
  future_agent_lab_return: "Future Agent Lab",
};

export const CHARACTERS = ["ada", "cog9", "nix"] as const;
export const BACKPACK_ITEMS = ["mission_compass"] as const;
export const BADGES = ["goal_badge"] as const;

export const EPISODE_ONE_NODES: StoryNode[] = [
  {
    node_key: "H1_N01",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "ada",
    bloom_level: "Remember",
    curriculum_concept: "Agent goal",
    fixed_story_beat: "Ada welcomes the ChronoCadet and frames COG-9 as a tool that needs a goal.",
    canonical_prompt_intent: "Student identifies that an agent needs a goal.",
    allowed_choice_types: ["action"],
    sort_order: 1,
    fallback: scene(
      "H1_N01",
      "future_agent_lab",
      "ada",
      "encouraging",
      "Professor Ada",
      "Welcome, ChronoCadet. TimeCity is losing one minute every hour. What should every helpful agent know first?",
      "TimeCity is losing time. Before COG-9 acts, it needs to know what it is trying to do.",
      [
        { id: "A", text: "Its goal.", choice_type: "action" },
        { id: "B", text: "Its favourite colour.", choice_type: "action" },
        { id: "C", text: "The fastest button.", choice_type: "action" },
      ],
      "Ada says good systems start with a clear purpose.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "irrelevant_preference", C: "speed_over_goal" },
      requires_followup: false,
      next_node_if_best: "H1_N02",
      next_node_if_partial: "H1_N02",
      next_node_if_retry: "H1_N01",
    },
  },
  {
    node_key: "H1_N02",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "cog9",
    bloom_level: "Understand",
    curriculum_concept: "Clear goals",
    fixed_story_beat: "COG-9 suggests the vague goal of fixing everything quickly.",
    canonical_prompt_intent: "Student sees that 'fix everything quickly' is too vague.",
    allowed_choice_types: ["why"],
    sort_order: 2,
    fallback: scene(
      "H1_N02",
      "future_agent_lab",
      "cog9",
      "excited",
      "COG-9",
      "Goal detected! I will fix everything quickly. Is that clear enough for safe action?",
      "COG-9 wants to fix everything quickly. Think about whether that tells it what success means.",
      [
        { id: "A", text: "Yes. Speed is always best.", choice_type: "why" },
        { id: "B", text: "Not yet. 'Everything' is too vague.", choice_type: "why" },
        { id: "C", text: "Let Nix decide.", choice_type: "why" },
      ],
      "A goal should be specific enough to guide the next safe action.",
    ),
    evaluation_key: {
      best_choice_ids: ["B"],
      partial_choice_ids: [],
      misconception_map: { A: "speed_over_safety", C: "outsource_judgement" },
      requires_followup: true,
      next_node_if_best: "H1_N03",
      next_node_if_partial: "H1_N03",
      next_node_if_retry: "H1_N02",
    },
  },
  {
    node_key: "H1_N03",
    room_slug: "future_agent_lab",
    room_title: ROOM_TITLES.future_agent_lab,
    character: "nix",
    bloom_level: "Analyse",
    curriculum_concept: "Safe action",
    fixed_story_beat: "Nix tempts COG-9 with a shiny AUTO-FIX shortcut.",
    canonical_prompt_intent: "Student resists an unsafe shortcut and asks what will change.",
    allowed_choice_types: ["ask_question"],
    sort_order: 3,
    fallback: scene(
      "H1_N03",
      "future_agent_lab",
      "nix",
      "mischievous",
      "Nix",
      "Press AUTO-FIX. It is big, shiny, and probably fine. What should you do before anyone presses it?",
      "Nix wants a shortcut. A safe agent asks what a button changes before using it.",
      [
        { id: "A", text: "Press it immediately.", choice_type: "ask_question" },
        { id: "B", text: "Ask what the button changes first.", choice_type: "ask_question" },
        { id: "C", text: "Hide the button under a box.", choice_type: "ask_question" },
      ],
      "Shortcuts can be useful, but only after you know their effect.",
    ),
    evaluation_key: {
      best_choice_ids: ["B"],
      partial_choice_ids: ["C"],
      misconception_map: { A: "unsafe_shortcut", C: "avoid_without_understanding" },
      requires_followup: false,
      next_node_if_best: "H1_N04",
      next_node_if_partial: "H1_N04",
      next_node_if_retry: "H1_N03",
    },
  },
  {
    node_key: "H1_N04",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "ada",
    bloom_level: "Apply",
    curriculum_concept: "Useful inputs",
    fixed_story_beat: "The Future Market loops after the unsafe shortcut.",
    canonical_prompt_intent: "Student identifies a useful clue/input.",
    allowed_choice_types: ["evidence"],
    sort_order: 4,
    fallback: scene(
      "H1_N04",
      "future_market",
      "ada",
      "thinking",
      "Professor Ada",
      "The Future Market is looping. Apple drones deliver the same crate again and again. What is the best first clue?",
      "Look for the clue that helps explain the system, not just a detail you can see.",
      [
        { id: "A", text: "The repeated delivery record.", choice_type: "evidence" },
        { id: "B", text: "The colour of the apple stall.", choice_type: "evidence" },
        { id: "C", text: "Nix's hat.", choice_type: "evidence" },
      ],
      "Repeated records are useful input evidence because the system is looping.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "irrelevant_visual_detail", C: "distracted_by_character" },
      requires_followup: false,
      next_node_if_best: "H1_N05",
      next_node_if_partial: "H1_N05",
      next_node_if_retry: "H1_N04",
    },
  },
  {
    node_key: "H1_N05",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "cog9",
    bloom_level: "Understand",
    curriculum_concept: "Input and output",
    fixed_story_beat: "COG-9 observes delivery records entering the system and price changes coming out.",
    canonical_prompt_intent: "Student distinguishes input from output.",
    allowed_choice_types: ["why"],
    sort_order: 5,
    fallback: scene(
      "H1_N05",
      "future_market",
      "cog9",
      "uncertain",
      "COG-9",
      "I see delivery records entering the system and price changes coming out. Which one is the input?",
      "Inputs go into a system. Outputs come out after the rule acts.",
      [
        { id: "A", text: "Delivery records.", choice_type: "why" },
        { id: "B", text: "Price changes.", choice_type: "why" },
        { id: "C", text: "The Goal Badge.", choice_type: "why" },
      ],
      "Ask: what does the system read before it changes something?",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: ["B"],
      misconception_map: { B: "output_as_input", C: "badge_as_data" },
      requires_followup: false,
      next_node_if_best: "H1_N06",
      next_node_if_partial: "H1_N06",
      next_node_if_retry: "H1_N05",
    },
  },
  {
    node_key: "H1_N06",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "ada",
    bloom_level: "Apply",
    curriculum_concept: "Goal, input, rule, output",
    fixed_story_beat: "The student uses the Mission Compass to name the parts of a safe agent action.",
    canonical_prompt_intent: "Student uses backpack item to identify goal, input, rule, and output.",
    allowed_choice_types: ["backpack"],
    required_backpack_item: "mission_compass",
    sort_order: 6,
    fallback: scene(
      "H1_N06",
      "future_market",
      "ada",
      "encouraging",
      "Professor Ada",
      "Use your Mission Compass. What should it identify before COG-9 acts?",
      "The Mission Compass helps find the parts of safe action: goal, input, rule, and output.",
      [
        { id: "A", text: "Goal, input, rule, and output.", choice_type: "backpack" },
        { id: "B", text: "Hat, apple, train, and steam.", choice_type: "backpack" },
        { id: "C", text: "Fastest path only.", choice_type: "backpack" },
      ],
      "Open the backpack and choose the compass before answering.",
      { required_item_slug: "mission_compass", allowed_item_slugs: ["mission_compass"] },
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "objects_not_system_parts", C: "speed_only" },
      requires_followup: false,
      next_node_if_best: "H1_N07",
      next_node_if_partial: "H1_N07",
      next_node_if_retry: "H1_N06",
    },
  },
  {
    node_key: "H1_N07",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "cog9",
    bloom_level: "Create",
    curriculum_concept: "Safe rule",
    fixed_story_beat: "The student helps write COG-9's first safe rule.",
    canonical_prompt_intent: "Student completes first safe agent rule.",
    allowed_choice_types: ["autocomplete_finish"],
    sort_order: 7,
    fallback: scene(
      "H1_N07",
      "future_market",
      "cog9",
      "uncertain",
      "COG-9",
      "Complete my first safe rule: 'When the city glitches, first...'",
      "Choose the ending that makes COG-9 check the goal and clues before acting.",
      [
        { id: "A", text: "define the goal and inspect the clues.", choice_type: "autocomplete_finish" },
        { id: "B", text: "press the biggest button.", choice_type: "autocomplete_finish" },
        { id: "C", text: "ask Nix to guess.", choice_type: "autocomplete_finish" },
      ],
      "A safe rule explains what to do before the repair starts.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "button_first", C: "unsafe_delegate" },
      requires_followup: true,
      next_node_if_best: "H1_N08",
      next_node_if_partial: "H1_N08",
      next_node_if_retry: "H1_N07",
    },
  },
  {
    node_key: "H1_N08",
    room_slug: "future_market",
    room_title: ROOM_TITLES.future_market,
    character: "ada",
    bloom_level: "Evaluate",
    curriculum_concept: "Explain why goals matter",
    fixed_story_beat: "Ada asks the student to explain why an agent needs a goal.",
    canonical_prompt_intent: "Student explains why an agent needs a goal before acting.",
    allowed_choice_types: ["why"],
    sort_order: 8,
    fallback: scene(
      "H1_N08",
      "future_market",
      "ada",
      "thinking",
      "Professor Ada",
      "Complete your explanation: I chose this because...",
      "Pick the explanation that connects the clue to safe agent action.",
      [
        { id: "A", text: "an agent needs a clear goal before acting.", choice_type: "why" },
        { id: "B", text: "fast buttons are exciting.", choice_type: "why" },
        { id: "C", text: "the market is colourful.", choice_type: "why" },
      ],
      "A good why answer says how the choice keeps COG-9 safe and useful.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "excitement_over_reasoning", C: "irrelevant_visual_detail" },
      requires_followup: false,
      next_node_if_best: "H1_N09",
      next_node_if_partial: "H1_N09",
      next_node_if_retry: "H1_N08",
    },
  },
  {
    node_key: "H1_N09",
    room_slug: "future_agent_lab_return",
    room_title: ROOM_TITLES.future_agent_lab_return,
    character: "cog9",
    bloom_level: "Understand",
    curriculum_concept: "Human-supervised AI",
    fixed_story_beat: "COG-9 returns to the lab with its first rule learned.",
    canonical_prompt_intent: "Student restates what COG-9 learned.",
    allowed_choice_types: ["why"],
    sort_order: 9,
    fallback: scene(
      "H1_N09",
      "future_agent_lab_return",
      "cog9",
      "excited",
      "COG-9",
      "You taught me my first rule. What did I learn?",
      "COG-9 can help, but it needs a goal and evidence before it acts.",
      [
        { id: "A", text: "I can help, but I need a goal and evidence.", choice_type: "why" },
        { id: "B", text: "I should always be fastest.", choice_type: "why" },
        { id: "C", text: "I should never ask humans anything.", choice_type: "why" },
      ],
      "Helpful agents still need human judgement and useful clues.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "speed_over_safety", C: "no_human_review" },
      requires_followup: false,
      next_node_if_best: "H1_N10",
      next_node_if_partial: "H1_N10",
      next_node_if_retry: "H1_N09",
    },
  },
  {
    node_key: "H1_N10",
    room_slug: "future_agent_lab_return",
    room_title: ROOM_TITLES.future_agent_lab_return,
    character: "ada",
    bloom_level: "Reflect",
    curriculum_concept: "Mission reflection",
    fixed_story_beat: "The Mission Compass points to 1888 and Episode 1 ends.",
    canonical_prompt_intent: "Preview next episode while ending Episode 1.",
    allowed_choice_types: ["action"],
    sort_order: 10,
    fallback: scene(
      "H1_N10",
      "future_agent_lab_return",
      "ada",
      "encouraging",
      "Professor Ada",
      "The Mission Compass points to the year 1888. The broken signal is older than Future TimeCity. What should we preview next?",
      "You have earned the Goal Badge. The next clue points to the Telegraph Office in 1888.",
      [
        { id: "A", text: "Follow the signal to the Telegraph Office.", choice_type: "action" },
        { id: "B", text: "Press AUTO-FIX again.", choice_type: "action" },
        { id: "C", text: "Put the compass away forever.", choice_type: "action" },
      ],
      "The safe next step follows the clue, not the shortcut.",
    ),
    evaluation_key: {
      best_choice_ids: ["A"],
      partial_choice_ids: [],
      misconception_map: { B: "repeat_unsafe_shortcut", C: "ignore_evidence" },
      requires_followup: false,
      next_node_if_best: "COMPLETE",
      next_node_if_partial: "COMPLETE",
      next_node_if_retry: "H1_N10",
    },
  },
];

export const NODE_BY_KEY = Object.fromEntries(EPISODE_ONE_NODES.map((node) => [node.node_key, node])) as Record<
  string,
  StoryNode
>;

export const FIRST_NODE_KEY = "H1_N01";
